### ISSUE TITLE
v3 tracking issue

### ISSUE THREAD

**Issue by ashkeel** [strimertul/strimertul#24]
## Features

- [x] Wails
- [x] Eventsub Websocket
- [x] Frontend KV rework (bypass auth, instant connection)
- [x] CLI command rework
- [x] Move logging to UI
- [x] Log files
- [x] https://github.com/strimertul/strimertul/issues/35
- [x] https://github.com/strimertul/strimertul/issues/32
- [x] https://github.com/strimertul/strimertul/issues/31
- [x] https://github.com/strimertul/strimertul/issues/42

## Issues

- [x] https://github.com/strimertul/strimertul/issues/29
- [x] https://github.com/strimertul/strimertul/issues/28
- [x] https://github.com/strimertul/strimertul/issues/27
- [x] https://github.com/strimertul/strimertul/issues/26
- [x] https://github.com/strimertul/strimertul/issues/25
- [x] https://github.com/strimertul/strimertul/issues/33
- [x] https://github.com/strimertul/strimertul/issues/34
- [x] https://github.com/strimertul/strimertul/issues/38
- [x] https://github.com/strimertul/strimertul/issues/40

## Removals/Deprecations

- [x] Badger
- [x] Stulbe

## Docs etc.

- [x] https://github.com/strimertul/strimertul/issues/41
- [x] Update README.md
- [x] Mascot
- [x] Final mascot icon

**Comment by ashkeel** [comment]
Added some issues to solve thanks to people clicking the wrong buttons on purpose (you know who you are, thanks!)

**Comment by ashkeel** [comment]
All issues found so far have been dealt with, new issues (found during RC) will be solved on a case-by-case basis!
